<?php

/**
 * Implementation of hook_menu().
 */
function webform_multifile_menu() {
  $items[] = array();
  
  $items['node/%webform_menu/submission/%webform_menu_submission/multifile_delete/%/%'] = array(
    'title' => 'Delete multifile upload',
    'load arguments' => array(1),
    'page callback' => 'webform_multifile_delete',
    'page arguments' => array(1, 3, 5, 6),
    'access callback' => 'webform_submission_access',
    'access arguments' => array(1, 3, 'edit'),
    'type' => MENU_CALLBACK,
  );

  $items['webform_multifile_convert_data'] = array(
    'title' => 'Convert old multifile field data',
    'page callback' => 'webform_multifile_convert_62_data',
    'access arguments' => array('edit all webform submissions'),
    'type' => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Implementation of hook_webform_component_info().
 */
function webform_multifile_webform_component_info() {
  $components = array();

  $components['multifile'] = array(
    'label' => t('Multifile'),
    'description' => t('Multifile Support For Webform File Uploads.'),
    'features' => array(
      'conditional' => FALSE,
      'attachment' => TRUE,
    ),
    'file' => 'multifile.inc',
  );

  return $components;
}

/**
 * Menu callback to delete a single file from a multifile upload.
 */
function webform_multifile_delete($webform, $submission, $component_id, $fid) {
  if ($file = db_fetch_object(db_query("SELECT * FROM {files} WHERE fid = %d", $fid))) {
    file_delete($file->filepath);
    db_query("DELETE FROM {files} WHERE fid = '%d'", $file->fid);
    // Update the submission data and re-save it without the deleted fid.
    $fids = unserialize($submission->data[$component_id]['value'][0]);
    $key = array_search($fid, $fids);
    unset($fids[$key]);
    $submission->data[$component_id]['value'][0] = serialize($fids);
    module_load_include('inc', 'webform', 'includes/webform.submissions');
    webform_submission_update($webform, $submission);
  }
  drupal_goto('node/' . $webform->nid . '/submission/' . $submission->sid . '/edit');
}

/**
 * Convert all old webform multifile data from the 6.2 multifile component in
 * comment #1 on http://drupal.org/node/623692 to a 6.3 API component.
 *
 * This function WILL modify your data and there's no going back, so please
 * ensure you have a db backup prior to running it.
 */
function webform_multifile_convert_62_data() {
  $result = db_query("SELECT * FROM {webform_component} WHERE type = 'multifile'");
  $count = 0;
  while ($component = db_fetch_object($result)) {
    $result2 = db_query("SELECT * FROM {webform_submitted_data} WHERE cid = %d", $component->cid);
    while ($submission = db_fetch_object($result2)) {
      $data = unserialize($submission->data);
      // The old multifile used an object to store the data.
      if (is_object($data[0])) {
        $count++;
        $fids = array();
        foreach ($data as $file) {
          $fids[] = $file->fid;
        }
        $data = serialize($fids);
        db_query("UPDATE {webform_submitted_data} SET data = '%s' WHERE nid = %d AND sid = %d AND cid = %d", array($data, $submission->nid, $submission->sid, $submission->cid));
      }
    }
  }

  return "Converted $count submissions";
}
